name: on_track
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  json_annotation: ^4.9.0
  flutter_screenutil: ^5.9.0
  flutter_local_notifications: ^18.0.1
  flutter_slidable: ^4.0.0
  easy_date_timeline: ^2.0.9
  gap: ^3.0.1
  animated_list_plus: ^0.5.2
  intl: ^0.19.0
  entry: ^1.0.0
  confetti: 0.8.0
  get: ^4.6.5
  shared_preferences: ^2.5.3
  uuid: ^4.4.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path: "assets/app_icon.png"

  # dart run flutter_launcher_icons
